// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package api

import (
	"context"
	"encoding/json"
	"fmt"
	"net/http"
	"time"

	"github.com/labstack/echo/v4"
	"github.com/oapi-codegen/runtime"
	strictecho "github.com/oapi-codegen/runtime/strictmiddleware/echo"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Error defines model for Error.
type Error struct {
	// Error Сообщение об ошибке
	Error string `json:"error"`
}

// Event defines model for Event.
type Event struct {
	// Id Уникальный идентификатор события
	Id string `json:"id"`

	// Payload Полезная нагрузка события (зависит от типа события)
	Payload map[string]interface{} `json:"payload"`

	// Timestamp Время события
	Timestamp time.Time `json:"timestamp"`

	// Type Тип события
	Type string `json:"type"`
}

// EventResponse defines model for EventResponse.
type EventResponse struct {
	Event Event `json:"event"`

	// Offset Смещение в партиции Kafka
	Offset int `json:"offset"`

	// Partition Партиция Kafka
	Partition int `json:"partition"`

	// Status Статус операции
	Status string `json:"status"`
}

// Movie defines model for Movie.
type Movie struct {
	// Description Описание фильма
	Description string `json:"description"`

	// Genres Жанры фильма
	Genres *[]string `json:"genres,omitempty"`

	// Id Уникальный идентификатор фильма
	Id int `json:"id"`

	// Rating Рейтинг фильма
	Rating float32 `json:"rating"`

	// Title Название фильма
	Title string `json:"title"`
}

// MovieEvent defines model for MovieEvent.
type MovieEvent struct {
	// Action Действие с фильмом
	Action string `json:"action"`

	// Description Описание фильма (опционально)
	Description *string `json:"description,omitempty"`

	// Genres Жанры фильма (опционально)
	Genres *[]string `json:"genres,omitempty"`

	// MovieId Идентификатор фильма
	MovieId int `json:"movie_id"`

	// Rating Рейтинг (опционально)
	Rating *float32 `json:"rating,omitempty"`

	// Title Название фильма
	Title string `json:"title"`

	// UserId Идентификатор пользователя (опционально)
	UserId *int `json:"user_id,omitempty"`
}

// MovieInput defines model for MovieInput.
type MovieInput struct {
	// Description Описание фильма
	Description string `json:"description"`

	// Genres Жанры фильма
	Genres *[]string `json:"genres,omitempty"`

	// Rating Рейтинг фильма
	Rating float32 `json:"rating"`

	// Title Название фильма
	Title string `json:"title"`
}

// Payment defines model for Payment.
type Payment struct {
	// Amount Сумма платежа
	Amount float32 `json:"amount"`

	// Id Уникальный идентификатор платежа
	Id int `json:"id"`

	// Timestamp Время совершения платежа
	Timestamp time.Time `json:"timestamp"`

	// UserId Идентификатор пользователя, совершившего платеж
	UserId int `json:"user_id"`
}

// PaymentEvent defines model for PaymentEvent.
type PaymentEvent struct {
	// Amount Сумма платежа
	Amount float32 `json:"amount"`

	// MethodType Тип метода оплаты (опционально)
	MethodType *string `json:"method_type,omitempty"`

	// PaymentId Идентификатор платежа
	PaymentId int `json:"payment_id"`

	// Status Статус платежа
	Status string `json:"status"`

	// Timestamp Время платежа
	Timestamp time.Time `json:"timestamp"`

	// UserId Идентификатор пользователя
	UserId int `json:"user_id"`
}

// PaymentInput defines model for PaymentInput.
type PaymentInput struct {
	// Amount Сумма платежа
	Amount float32 `json:"amount"`

	// UserId Идентификатор пользователя, совершающего платеж
	UserId int `json:"user_id"`
}

// Subscription defines model for Subscription.
type Subscription struct {
	// EndDate Дата окончания подписки
	EndDate time.Time `json:"end_date"`

	// Id Уникальный идентификатор подписки
	Id int `json:"id"`

	// PlanType Тип плана подписки
	PlanType string `json:"plan_type"`

	// StartDate Дата начала подписки
	StartDate time.Time `json:"start_date"`

	// UserId Идентификатор пользователя, оформившего подписку
	UserId int `json:"user_id"`
}

// SubscriptionInput defines model for SubscriptionInput.
type SubscriptionInput struct {
	// EndDate Дата окончания подписки
	EndDate time.Time `json:"end_date"`

	// PlanType Тип плана подписки
	PlanType string `json:"plan_type"`

	// StartDate Дата начала подписки
	StartDate time.Time `json:"start_date"`

	// UserId Идентификатор пользователя, оформляющего подписку
	UserId int `json:"user_id"`
}

// User defines model for User.
type User struct {
	// Email Email пользователя
	Email openapi_types.Email `json:"email"`

	// Id Уникальный идентификатор пользователя
	Id int `json:"id"`

	// Username Имя пользователя
	Username string `json:"username"`
}

// UserEvent defines model for UserEvent.
type UserEvent struct {
	// Action Действие пользователя
	Action string `json:"action"`

	// Email Email пользователя (опционально)
	Email *string `json:"email,omitempty"`

	// Timestamp Время события
	Timestamp time.Time `json:"timestamp"`

	// UserId Идентификатор пользователя
	UserId int `json:"user_id"`

	// Username Имя пользователя (опционально)
	Username *string `json:"username,omitempty"`
}

// UserInput defines model for UserInput.
type UserInput struct {
	// Email Email пользователя
	Email openapi_types.Email `json:"email"`

	// Username Имя пользователя
	Username string `json:"username"`
}

// GetAllPaymentsParams defines parameters for GetAllPayments.
type GetAllPaymentsParams struct {
	// UserId ID пользователя для фильтрации платежей
	UserId *int `form:"user_id,omitempty" json:"user_id,omitempty"`
}

// GetAllSubscriptionsParams defines parameters for GetAllSubscriptions.
type GetAllSubscriptionsParams struct {
	// UserId ID пользователя для фильтрации подписок
	UserId *int `form:"user_id,omitempty" json:"user_id,omitempty"`
}

// CreateMovieEventJSONRequestBody defines body for CreateMovieEvent for application/json ContentType.
type CreateMovieEventJSONRequestBody = MovieEvent

// CreatePaymentEventJSONRequestBody defines body for CreatePaymentEvent for application/json ContentType.
type CreatePaymentEventJSONRequestBody = PaymentEvent

// CreateUserEventJSONRequestBody defines body for CreateUserEvent for application/json ContentType.
type CreateUserEventJSONRequestBody = UserEvent

// CreateMovieJSONRequestBody defines body for CreateMovie for application/json ContentType.
type CreateMovieJSONRequestBody = MovieInput

// CreatePaymentJSONRequestBody defines body for CreatePayment for application/json ContentType.
type CreatePaymentJSONRequestBody = PaymentInput

// CreateSubscriptionJSONRequestBody defines body for CreateSubscription for application/json ContentType.
type CreateSubscriptionJSONRequestBody = SubscriptionInput

// CreateUserJSONRequestBody defines body for CreateUser for application/json ContentType.
type CreateUserJSONRequestBody = UserInput

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Проверка работоспособности микросервиса событий
	// (GET /api/events/health)
	GetEventsServiceHealth(ctx echo.Context) error
	// Создание события фильма
	// (POST /api/events/movie)
	CreateMovieEvent(ctx echo.Context) error
	// Создание события платежа
	// (POST /api/events/payment)
	CreatePaymentEvent(ctx echo.Context) error
	// Создание события пользователя
	// (POST /api/events/user)
	CreateUserEvent(ctx echo.Context) error
	// Получение списка всех фильмов
	// (GET /api/movies)
	GetAllMovies(ctx echo.Context) error
	// Создание нового фильма
	// (POST /api/movies)
	CreateMovie(ctx echo.Context) error
	// Проверка работоспособности микросервиса фильмов
	// (GET /api/movies/health)
	GetMoviesServiceHealth(ctx echo.Context) error
	// Получение списка всех платежей
	// (GET /api/payments)
	GetAllPayments(ctx echo.Context, params GetAllPaymentsParams) error
	// Создание нового платежа
	// (POST /api/payments)
	CreatePayment(ctx echo.Context) error
	// Получение списка всех подписок
	// (GET /api/subscriptions)
	GetAllSubscriptions(ctx echo.Context, params GetAllSubscriptionsParams) error
	// Создание новой подписки
	// (POST /api/subscriptions)
	CreateSubscription(ctx echo.Context) error
	// Получение списка всех пользователей
	// (GET /api/users)
	GetAllUsers(ctx echo.Context) error
	// Создание нового пользователя
	// (POST /api/users)
	CreateUser(ctx echo.Context) error
	// Проверка работоспособности API Gateway
	// (GET /health)
	GetProxyHealth(ctx echo.Context) error
}

// ServerInterfaceWrapper converts echo contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

// GetEventsServiceHealth converts echo context to params.
func (w *ServerInterfaceWrapper) GetEventsServiceHealth(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetEventsServiceHealth(ctx)
	return err
}

// CreateMovieEvent converts echo context to params.
func (w *ServerInterfaceWrapper) CreateMovieEvent(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.CreateMovieEvent(ctx)
	return err
}

// CreatePaymentEvent converts echo context to params.
func (w *ServerInterfaceWrapper) CreatePaymentEvent(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.CreatePaymentEvent(ctx)
	return err
}

// CreateUserEvent converts echo context to params.
func (w *ServerInterfaceWrapper) CreateUserEvent(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.CreateUserEvent(ctx)
	return err
}

// GetAllMovies converts echo context to params.
func (w *ServerInterfaceWrapper) GetAllMovies(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetAllMovies(ctx)
	return err
}

// CreateMovie converts echo context to params.
func (w *ServerInterfaceWrapper) CreateMovie(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.CreateMovie(ctx)
	return err
}

// GetMoviesServiceHealth converts echo context to params.
func (w *ServerInterfaceWrapper) GetMoviesServiceHealth(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetMoviesServiceHealth(ctx)
	return err
}

// GetAllPayments converts echo context to params.
func (w *ServerInterfaceWrapper) GetAllPayments(ctx echo.Context) error {
	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetAllPaymentsParams
	// ------------- Optional query parameter "user_id" -------------

	err = runtime.BindQueryParameter("form", true, false, "user_id", ctx.QueryParams(), &params.UserId)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter user_id: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetAllPayments(ctx, params)
	return err
}

// CreatePayment converts echo context to params.
func (w *ServerInterfaceWrapper) CreatePayment(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.CreatePayment(ctx)
	return err
}

// GetAllSubscriptions converts echo context to params.
func (w *ServerInterfaceWrapper) GetAllSubscriptions(ctx echo.Context) error {
	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetAllSubscriptionsParams
	// ------------- Optional query parameter "user_id" -------------

	err = runtime.BindQueryParameter("form", true, false, "user_id", ctx.QueryParams(), &params.UserId)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter user_id: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetAllSubscriptions(ctx, params)
	return err
}

// CreateSubscription converts echo context to params.
func (w *ServerInterfaceWrapper) CreateSubscription(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.CreateSubscription(ctx)
	return err
}

// GetAllUsers converts echo context to params.
func (w *ServerInterfaceWrapper) GetAllUsers(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetAllUsers(ctx)
	return err
}

// CreateUser converts echo context to params.
func (w *ServerInterfaceWrapper) CreateUser(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.CreateUser(ctx)
	return err
}

// GetProxyHealth converts echo context to params.
func (w *ServerInterfaceWrapper) GetProxyHealth(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetProxyHealth(ctx)
	return err
}

// This is a simple interface which specifies echo.Route addition functions which
// are present on both echo.Echo and echo.Group, since we want to allow using
// either of them for path registration
type EchoRouter interface {
	CONNECT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	DELETE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	GET(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	HEAD(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	OPTIONS(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PATCH(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	POST(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PUT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	TRACE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
}

// RegisterHandlers adds each server route to the EchoRouter.
func RegisterHandlers(router EchoRouter, si ServerInterface) {
	RegisterHandlersWithBaseURL(router, si, "")
}

// Registers handlers, and prepends BaseURL to the paths, so that the paths
// can be served under a prefix.
func RegisterHandlersWithBaseURL(router EchoRouter, si ServerInterface, baseURL string) {

	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	router.GET(baseURL+"/api/events/health", wrapper.GetEventsServiceHealth)
	router.POST(baseURL+"/api/events/movie", wrapper.CreateMovieEvent)
	router.POST(baseURL+"/api/events/payment", wrapper.CreatePaymentEvent)
	router.POST(baseURL+"/api/events/user", wrapper.CreateUserEvent)
	router.GET(baseURL+"/api/movies", wrapper.GetAllMovies)
	router.POST(baseURL+"/api/movies", wrapper.CreateMovie)
	router.GET(baseURL+"/api/movies/health", wrapper.GetMoviesServiceHealth)
	router.GET(baseURL+"/api/payments", wrapper.GetAllPayments)
	router.POST(baseURL+"/api/payments", wrapper.CreatePayment)
	router.GET(baseURL+"/api/subscriptions", wrapper.GetAllSubscriptions)
	router.POST(baseURL+"/api/subscriptions", wrapper.CreateSubscription)
	router.GET(baseURL+"/api/users", wrapper.GetAllUsers)
	router.POST(baseURL+"/api/users", wrapper.CreateUser)
	router.GET(baseURL+"/health", wrapper.GetProxyHealth)

}

type GetEventsServiceHealthRequestObject struct {
}

type GetEventsServiceHealthResponseObject interface {
	VisitGetEventsServiceHealthResponse(w http.ResponseWriter) error
}

type GetEventsServiceHealth200JSONResponse struct {
	Status *bool `json:"status,omitempty"`
}

func (response GetEventsServiceHealth200JSONResponse) VisitGetEventsServiceHealthResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type CreateMovieEventRequestObject struct {
	Body *CreateMovieEventJSONRequestBody
}

type CreateMovieEventResponseObject interface {
	VisitCreateMovieEventResponse(w http.ResponseWriter) error
}

type CreateMovieEvent201JSONResponse EventResponse

func (response CreateMovieEvent201JSONResponse) VisitCreateMovieEventResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)

	return json.NewEncoder(w).Encode(response)
}

type CreateMovieEvent400JSONResponse Error

func (response CreateMovieEvent400JSONResponse) VisitCreateMovieEventResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type CreateMovieEvent500JSONResponse Error

func (response CreateMovieEvent500JSONResponse) VisitCreateMovieEventResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type CreatePaymentEventRequestObject struct {
	Body *CreatePaymentEventJSONRequestBody
}

type CreatePaymentEventResponseObject interface {
	VisitCreatePaymentEventResponse(w http.ResponseWriter) error
}

type CreatePaymentEvent201JSONResponse EventResponse

func (response CreatePaymentEvent201JSONResponse) VisitCreatePaymentEventResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)

	return json.NewEncoder(w).Encode(response)
}

type CreatePaymentEvent400JSONResponse Error

func (response CreatePaymentEvent400JSONResponse) VisitCreatePaymentEventResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type CreatePaymentEvent500JSONResponse Error

func (response CreatePaymentEvent500JSONResponse) VisitCreatePaymentEventResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type CreateUserEventRequestObject struct {
	Body *CreateUserEventJSONRequestBody
}

type CreateUserEventResponseObject interface {
	VisitCreateUserEventResponse(w http.ResponseWriter) error
}

type CreateUserEvent201JSONResponse EventResponse

func (response CreateUserEvent201JSONResponse) VisitCreateUserEventResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)

	return json.NewEncoder(w).Encode(response)
}

type CreateUserEvent400JSONResponse Error

func (response CreateUserEvent400JSONResponse) VisitCreateUserEventResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type CreateUserEvent500JSONResponse Error

func (response CreateUserEvent500JSONResponse) VisitCreateUserEventResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type GetAllMoviesRequestObject struct {
}

type GetAllMoviesResponseObject interface {
	VisitGetAllMoviesResponse(w http.ResponseWriter) error
}

type GetAllMovies200JSONResponse []Movie

func (response GetAllMovies200JSONResponse) VisitGetAllMoviesResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetAllMovies500JSONResponse Error

func (response GetAllMovies500JSONResponse) VisitGetAllMoviesResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type CreateMovieRequestObject struct {
	Body *CreateMovieJSONRequestBody
}

type CreateMovieResponseObject interface {
	VisitCreateMovieResponse(w http.ResponseWriter) error
}

type CreateMovie201JSONResponse Movie

func (response CreateMovie201JSONResponse) VisitCreateMovieResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)

	return json.NewEncoder(w).Encode(response)
}

type CreateMovie400JSONResponse Error

func (response CreateMovie400JSONResponse) VisitCreateMovieResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type CreateMovie500JSONResponse Error

func (response CreateMovie500JSONResponse) VisitCreateMovieResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type GetMoviesServiceHealthRequestObject struct {
}

type GetMoviesServiceHealthResponseObject interface {
	VisitGetMoviesServiceHealthResponse(w http.ResponseWriter) error
}

type GetMoviesServiceHealth200JSONResponse struct {
	Status *bool `json:"status,omitempty"`
}

func (response GetMoviesServiceHealth200JSONResponse) VisitGetMoviesServiceHealthResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetAllPaymentsRequestObject struct {
	Params GetAllPaymentsParams
}

type GetAllPaymentsResponseObject interface {
	VisitGetAllPaymentsResponse(w http.ResponseWriter) error
}

type GetAllPayments200JSONResponse []Payment

func (response GetAllPayments200JSONResponse) VisitGetAllPaymentsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetAllPayments500JSONResponse Error

func (response GetAllPayments500JSONResponse) VisitGetAllPaymentsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type CreatePaymentRequestObject struct {
	Body *CreatePaymentJSONRequestBody
}

type CreatePaymentResponseObject interface {
	VisitCreatePaymentResponse(w http.ResponseWriter) error
}

type CreatePayment201JSONResponse Payment

func (response CreatePayment201JSONResponse) VisitCreatePaymentResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)

	return json.NewEncoder(w).Encode(response)
}

type CreatePayment400JSONResponse Error

func (response CreatePayment400JSONResponse) VisitCreatePaymentResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type CreatePayment500JSONResponse Error

func (response CreatePayment500JSONResponse) VisitCreatePaymentResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type GetAllSubscriptionsRequestObject struct {
	Params GetAllSubscriptionsParams
}

type GetAllSubscriptionsResponseObject interface {
	VisitGetAllSubscriptionsResponse(w http.ResponseWriter) error
}

type GetAllSubscriptions200JSONResponse []Subscription

func (response GetAllSubscriptions200JSONResponse) VisitGetAllSubscriptionsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetAllSubscriptions500JSONResponse Error

func (response GetAllSubscriptions500JSONResponse) VisitGetAllSubscriptionsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type CreateSubscriptionRequestObject struct {
	Body *CreateSubscriptionJSONRequestBody
}

type CreateSubscriptionResponseObject interface {
	VisitCreateSubscriptionResponse(w http.ResponseWriter) error
}

type CreateSubscription201JSONResponse Subscription

func (response CreateSubscription201JSONResponse) VisitCreateSubscriptionResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)

	return json.NewEncoder(w).Encode(response)
}

type CreateSubscription400JSONResponse Error

func (response CreateSubscription400JSONResponse) VisitCreateSubscriptionResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type CreateSubscription500JSONResponse Error

func (response CreateSubscription500JSONResponse) VisitCreateSubscriptionResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type GetAllUsersRequestObject struct {
}

type GetAllUsersResponseObject interface {
	VisitGetAllUsersResponse(w http.ResponseWriter) error
}

type GetAllUsers200JSONResponse []User

func (response GetAllUsers200JSONResponse) VisitGetAllUsersResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetAllUsers500JSONResponse Error

func (response GetAllUsers500JSONResponse) VisitGetAllUsersResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type CreateUserRequestObject struct {
	Body *CreateUserJSONRequestBody
}

type CreateUserResponseObject interface {
	VisitCreateUserResponse(w http.ResponseWriter) error
}

type CreateUser201JSONResponse User

func (response CreateUser201JSONResponse) VisitCreateUserResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)

	return json.NewEncoder(w).Encode(response)
}

type CreateUser400JSONResponse Error

func (response CreateUser400JSONResponse) VisitCreateUserResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type CreateUser500JSONResponse Error

func (response CreateUser500JSONResponse) VisitCreateUserResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type GetProxyHealthRequestObject struct {
}

type GetProxyHealthResponseObject interface {
	VisitGetProxyHealthResponse(w http.ResponseWriter) error
}

type GetProxyHealth200TextResponse string

func (response GetProxyHealth200TextResponse) VisitGetProxyHealthResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "text/plain")
	w.WriteHeader(200)

	_, err := w.Write([]byte(response))
	return err
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// Проверка работоспособности микросервиса событий
	// (GET /api/events/health)
	GetEventsServiceHealth(ctx context.Context, request GetEventsServiceHealthRequestObject) (GetEventsServiceHealthResponseObject, error)
	// Создание события фильма
	// (POST /api/events/movie)
	CreateMovieEvent(ctx context.Context, request CreateMovieEventRequestObject) (CreateMovieEventResponseObject, error)
	// Создание события платежа
	// (POST /api/events/payment)
	CreatePaymentEvent(ctx context.Context, request CreatePaymentEventRequestObject) (CreatePaymentEventResponseObject, error)
	// Создание события пользователя
	// (POST /api/events/user)
	CreateUserEvent(ctx context.Context, request CreateUserEventRequestObject) (CreateUserEventResponseObject, error)
	// Получение списка всех фильмов
	// (GET /api/movies)
	GetAllMovies(ctx context.Context, request GetAllMoviesRequestObject) (GetAllMoviesResponseObject, error)
	// Создание нового фильма
	// (POST /api/movies)
	CreateMovie(ctx context.Context, request CreateMovieRequestObject) (CreateMovieResponseObject, error)
	// Проверка работоспособности микросервиса фильмов
	// (GET /api/movies/health)
	GetMoviesServiceHealth(ctx context.Context, request GetMoviesServiceHealthRequestObject) (GetMoviesServiceHealthResponseObject, error)
	// Получение списка всех платежей
	// (GET /api/payments)
	GetAllPayments(ctx context.Context, request GetAllPaymentsRequestObject) (GetAllPaymentsResponseObject, error)
	// Создание нового платежа
	// (POST /api/payments)
	CreatePayment(ctx context.Context, request CreatePaymentRequestObject) (CreatePaymentResponseObject, error)
	// Получение списка всех подписок
	// (GET /api/subscriptions)
	GetAllSubscriptions(ctx context.Context, request GetAllSubscriptionsRequestObject) (GetAllSubscriptionsResponseObject, error)
	// Создание новой подписки
	// (POST /api/subscriptions)
	CreateSubscription(ctx context.Context, request CreateSubscriptionRequestObject) (CreateSubscriptionResponseObject, error)
	// Получение списка всех пользователей
	// (GET /api/users)
	GetAllUsers(ctx context.Context, request GetAllUsersRequestObject) (GetAllUsersResponseObject, error)
	// Создание нового пользователя
	// (POST /api/users)
	CreateUser(ctx context.Context, request CreateUserRequestObject) (CreateUserResponseObject, error)
	// Проверка работоспособности API Gateway
	// (GET /health)
	GetProxyHealth(ctx context.Context, request GetProxyHealthRequestObject) (GetProxyHealthResponseObject, error)
}

type StrictHandlerFunc = strictecho.StrictEchoHandlerFunc
type StrictMiddlewareFunc = strictecho.StrictEchoMiddlewareFunc

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
}

// GetEventsServiceHealth operation middleware
func (sh *strictHandler) GetEventsServiceHealth(ctx echo.Context) error {
	var request GetEventsServiceHealthRequestObject

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetEventsServiceHealth(ctx.Request().Context(), request.(GetEventsServiceHealthRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetEventsServiceHealth")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(GetEventsServiceHealthResponseObject); ok {
		return validResponse.VisitGetEventsServiceHealthResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// CreateMovieEvent operation middleware
func (sh *strictHandler) CreateMovieEvent(ctx echo.Context) error {
	var request CreateMovieEventRequestObject

	var body CreateMovieEventJSONRequestBody
	if err := ctx.Bind(&body); err != nil {
		return err
	}
	request.Body = &body

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.CreateMovieEvent(ctx.Request().Context(), request.(CreateMovieEventRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateMovieEvent")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(CreateMovieEventResponseObject); ok {
		return validResponse.VisitCreateMovieEventResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// CreatePaymentEvent operation middleware
func (sh *strictHandler) CreatePaymentEvent(ctx echo.Context) error {
	var request CreatePaymentEventRequestObject

	var body CreatePaymentEventJSONRequestBody
	if err := ctx.Bind(&body); err != nil {
		return err
	}
	request.Body = &body

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.CreatePaymentEvent(ctx.Request().Context(), request.(CreatePaymentEventRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreatePaymentEvent")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(CreatePaymentEventResponseObject); ok {
		return validResponse.VisitCreatePaymentEventResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// CreateUserEvent operation middleware
func (sh *strictHandler) CreateUserEvent(ctx echo.Context) error {
	var request CreateUserEventRequestObject

	var body CreateUserEventJSONRequestBody
	if err := ctx.Bind(&body); err != nil {
		return err
	}
	request.Body = &body

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.CreateUserEvent(ctx.Request().Context(), request.(CreateUserEventRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateUserEvent")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(CreateUserEventResponseObject); ok {
		return validResponse.VisitCreateUserEventResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// GetAllMovies operation middleware
func (sh *strictHandler) GetAllMovies(ctx echo.Context) error {
	var request GetAllMoviesRequestObject

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetAllMovies(ctx.Request().Context(), request.(GetAllMoviesRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetAllMovies")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(GetAllMoviesResponseObject); ok {
		return validResponse.VisitGetAllMoviesResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// CreateMovie operation middleware
func (sh *strictHandler) CreateMovie(ctx echo.Context) error {
	var request CreateMovieRequestObject

	var body CreateMovieJSONRequestBody
	if err := ctx.Bind(&body); err != nil {
		return err
	}
	request.Body = &body

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.CreateMovie(ctx.Request().Context(), request.(CreateMovieRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateMovie")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(CreateMovieResponseObject); ok {
		return validResponse.VisitCreateMovieResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// GetMoviesServiceHealth operation middleware
func (sh *strictHandler) GetMoviesServiceHealth(ctx echo.Context) error {
	var request GetMoviesServiceHealthRequestObject

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetMoviesServiceHealth(ctx.Request().Context(), request.(GetMoviesServiceHealthRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetMoviesServiceHealth")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(GetMoviesServiceHealthResponseObject); ok {
		return validResponse.VisitGetMoviesServiceHealthResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// GetAllPayments operation middleware
func (sh *strictHandler) GetAllPayments(ctx echo.Context, params GetAllPaymentsParams) error {
	var request GetAllPaymentsRequestObject

	request.Params = params

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetAllPayments(ctx.Request().Context(), request.(GetAllPaymentsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetAllPayments")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(GetAllPaymentsResponseObject); ok {
		return validResponse.VisitGetAllPaymentsResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// CreatePayment operation middleware
func (sh *strictHandler) CreatePayment(ctx echo.Context) error {
	var request CreatePaymentRequestObject

	var body CreatePaymentJSONRequestBody
	if err := ctx.Bind(&body); err != nil {
		return err
	}
	request.Body = &body

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.CreatePayment(ctx.Request().Context(), request.(CreatePaymentRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreatePayment")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(CreatePaymentResponseObject); ok {
		return validResponse.VisitCreatePaymentResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// GetAllSubscriptions operation middleware
func (sh *strictHandler) GetAllSubscriptions(ctx echo.Context, params GetAllSubscriptionsParams) error {
	var request GetAllSubscriptionsRequestObject

	request.Params = params

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetAllSubscriptions(ctx.Request().Context(), request.(GetAllSubscriptionsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetAllSubscriptions")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(GetAllSubscriptionsResponseObject); ok {
		return validResponse.VisitGetAllSubscriptionsResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// CreateSubscription operation middleware
func (sh *strictHandler) CreateSubscription(ctx echo.Context) error {
	var request CreateSubscriptionRequestObject

	var body CreateSubscriptionJSONRequestBody
	if err := ctx.Bind(&body); err != nil {
		return err
	}
	request.Body = &body

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.CreateSubscription(ctx.Request().Context(), request.(CreateSubscriptionRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateSubscription")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(CreateSubscriptionResponseObject); ok {
		return validResponse.VisitCreateSubscriptionResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// GetAllUsers operation middleware
func (sh *strictHandler) GetAllUsers(ctx echo.Context) error {
	var request GetAllUsersRequestObject

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetAllUsers(ctx.Request().Context(), request.(GetAllUsersRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetAllUsers")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(GetAllUsersResponseObject); ok {
		return validResponse.VisitGetAllUsersResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// CreateUser operation middleware
func (sh *strictHandler) CreateUser(ctx echo.Context) error {
	var request CreateUserRequestObject

	var body CreateUserJSONRequestBody
	if err := ctx.Bind(&body); err != nil {
		return err
	}
	request.Body = &body

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.CreateUser(ctx.Request().Context(), request.(CreateUserRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateUser")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(CreateUserResponseObject); ok {
		return validResponse.VisitCreateUserResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// GetProxyHealth operation middleware
func (sh *strictHandler) GetProxyHealth(ctx echo.Context) error {
	var request GetProxyHealthRequestObject

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetProxyHealth(ctx.Request().Context(), request.(GetProxyHealthRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetProxyHealth")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(GetProxyHealthResponseObject); ok {
		return validResponse.VisitGetProxyHealthResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}
