// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
)

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xcW28bx/X/Kov5/x8SgKIoKQZsPkVNnVQoggqV89LEMEbkSNyEe8nuUAkRCNAlaRIo",
	"iIogKPrQNHXbD0DLZkTrsvoKZ75RMWf2yp0llxJJOwWfLO+SM+ec+f3OdaQvSMOxXMdmNvdJ/QviN1rM",
	"ovjjQ89zPPmD6zku87jJ8DGLHjeZ3/BMl5uOTeoEnkIAATwT30IfrmEAfUP+14BAfAMDeAYX0CcVwj6n",
	"lttmpE42bM48m7aNLebtMc9Q21UI77rytc89094l+/sV4rFPO6bHmqT+Ybj74/hjzvbHrMHJfoU83GM2",
	"z4trNjWy/hslvIAeXIrv4FqcwEsDBvBCii6OYCC+VK/FEQTiwBCHqNkJvjrNaGE5eyZbWlnaM9lnrJkX",
	"v0Jc2m07VCfFzxDAJfThHK6hJ04N+Q88FwfiGM7l7kP7Gm/AOfTgDAbiEAbiSJr2yJDv4Cb34TeJxkTc",
	"tJjPqeVqhPlBHEAfrsTpKG1Xa6trS7WVpZV7j1beqq/V6rXan0iF7DieRTmpkyblbEnuojOEepDb+F9S",
	"/rEmHgsMMzZ+Ws/E/IWQ+SPzXcf2mQbpEaL+32M7pE7+bznhynJIlGUFu/0KcXZ2fMa1xLiCfpoWZ4Y8",
	"MHGAuv4ZBjAwfk93PqFprd9ajeU1bc52maew5HFTratBU2pJcZpfsqZb0eeUd3yd1OJI4l8ci0NJ5Bvo",
	"iwPoKXEzx+N3Gg3m+2MPKNwprURstEpoa90hvY/HnzucjLg56f8BN0iTXmhzJLTk+hX0MtKvG7xlsh3j",
	"s5Zj+JzRtm80HM91PMqZ4bOGx7hv8JbndHZbBm8xo+Mzw9kxmh6j1pLfolJXg7NGy3bazm7XMH1j19xj",
	"Nn7YtPeY5zODU/8T+S23TW0uv0Btw2wyapg2d/CTlmk35Seo8U71YfUPVR2BdpntMd1Z/VXqKQ7ESaGe",
	"H5Kthrn0rkkqZL0R2v5RyzPbbYbe1OTMwpULWEuo59Gu/P9U/GmBlCs6hHpUWkyz6T+hDy/R/V3D88I1",
	"71fvpxzUTtuhPLGt3bG21S7c5G2dd/oJenAOZ+OBtGE3mBtatoynwv0qme1iXQtpUBDjaKOABj+iiQ7F",
	"kYwaUvrDtAIBXGVUKI5htyeb8YZ0Hug2AoxvCBAI3hxiocT/0jazm0inCJl3J0Gp/fPsmIgSGKCeaInx",
	"t7lyoIyu96v3XjUfKqTjM29Sg8GNTJfEd3AOgRRAHEEfLjEtGq+1xqpDrIwPMeEmjbGgZ+OG7Xb4IjK9",
	"LpHpfy5QTBwjNmnX0gcIy+nY2txUHMMV+km4gcuQVL9kJX5QffCgjGWmkRkUS6H1ixMUNGcygRXfqCxc",
	"FluFO92typmma6tkRR/AGSrwHIKM+JM5OnRxkZSVCBppW46AVlECMg98WYy3nOaTkWUkllpHEMALuWUQ",
	"bSpOyuUhDY81Tf6kQb2iUl4a4RbHOwmoy5VkxfCVRWqbcX0mV44xvwZyTIb61NFp0R9Xp6VoUBD550KD",
	"GTqYnvge+xR3czA56+oMudXZzmRJQ50Xu/lEAklb0kihkNwXksriaxVyFWol8VV+dTHUpkDcrqwura08",
	"Wl2r33tQv/egPG6nFNoKpdP6AZmSjfF2eEbSnY3W3fWYZXYsnWY+px4fa+tr6KGdL8ftFHmH2sqjmnQN",
	"rzB0QiC+lB+Bq+HAmRJfHN8peCZHlLFkJQHwOOwXeJLXjQALLE4Li5fiNOtl74DGuwLxA5/pBjwWNdt5",
	"xR/Kx6WiMfnYadnVpsPeDh9VG46VtrzaYZZ+dvJ8QR25TS2mPfOriF5ldH/SdEoOLOI9K6FRio7prp2/",
	"UrJ7bNf0OfP0qeOtcFEu7y4AzC2z11kNsOaYvd4BjeUtXgqmqWwuas+MTpElWoui2qvzLHMmdwley6+Y",
	"9o4jJWo4NqcNnrIR8Tuu63j87YZpM4vS7a7vh8oqNcg7+GJdvjAeMWrl+vRkfXNDcuEG+jgSjICpxoPw",
	"AsGCo+RDVPZKnBipRSsGnMEFXIrvZbjFmIVD6iuEVQCXagY9MDDBuhAHEIhDnBLihFqcVD+yP7LhabI+",
	"9NLrG3CDjH2Br3twJuWR1XvIXwikn48K+DB8iuNY8GP8Pn4vbuqkm25SrErhscZvU9WYfIYKZbMKfF79",
	"yIa/iAPxldQa+nCBdfiBmrunLZg2GmqTNRj+1Fe6D+ASAvglGQwPDDgTJ+hLlE4y2PVHGTjuVmfxsL65",
	"QSpkj3m+QsJKtVat4ZDaZTZ1TVIna9VadQ2nsbyF5FymrrmMY1h/ucVom7fk013tSPsHCOAcznAi/G2o",
	"pzrGsD2BJ/MMAvSCEoJBeKjX8ifpJwu0GrrIAC8JCu1RTJabpE7eY6oL5W8xb89ssN8pWSX/1CAftVmt",
	"1SJihYGTum7bbOA6yx/7KmiqIX7eUSUtmJj73OuwmMPbjtNm1Ebaa2g9nMCEJPwmSl4CDMt9cYQL+B3L",
	"ol4XZ/jSHKocVxdApmlGTnd96ZvCw30s904fuhUP2h2fF7TRnyusS/DiPRUE+DXKHOB8MbVnH7sLZ+IU",
	"r61ch8jXjSCzB/yOxyhnqXmncq3M579xmt2JTnXUxY3UBrpD+1HJjAQcuocz1NpP/L7EyH4OiCtTEzl7",
	"X0Un9dO0/Q1JxQh5ECg1zuEFahZId/DWhCwZKRzezNIJ9ZP0l9J/o7+/kE5Q8UDi4kZBV0pzby7S/ADX",
	"4hghrDzsqQxqySU1JI7iEd54Gabo05QNB2OxEXFOUSzPOTc1sZkx6zKxrph3mUb/bJiX2WJC7uX6pwv2",
	"LdhXjI5x/OtEHZDZk0+ThsqUsYCGSc0/Gw4m609OwKI6aUHFBRXL4KSQlJiB+pOWHWGhFsCFLJ+kzF9l",
	"U8wzZOBAfBWNh3uh2NL6V9g1zpUY6+32+0qaOxYW8f2Vsblo/k7LhLXErwQ4eO1dHIuv48I3PkP55YIz",
	"TOEmhMnj/UqR3/4Ri6R0T0F5bDRZsq6B0EiV78ejipFZ1iGqYTbWFacvNiYNnBQP5+yHQ9xqxP5PbOMR",
	"vnfheafieeNs5Lm0r74AiTmT9bWvuNMzzPCcG1Y+eNHpmcyMhZ2esNycSojN5Np9qWzWmeKve+ni6mYk",
	"BP4qCLUYZ54Ud1iWjd8Wzzgi5xdqjlwKfzklJxipEFOu92mHed2kf54MNhJs5Oatj+cR/aNrm4v4n4n/",
	"mnOMgB3jeEQOMLp2U8ZL7VACvpkGyWx7I+XygWy5+1pkBDGWNaL/nLL2IiuYa1ZQ2BhJMSkKEn7qetK0",
	"IkUyT1NvykWKrYwkswsXGele+3CRuTq5iBnDMWP4MCOkZ2F9+8BxLL7PXdsqHTwyZzebCJK/XVgijGRu",
	"0b0WgSSLcm00yQzpR/b4eouYMt2Y8lJ39bKIaVFgkS50egFF101/OXQboyCufICCzMNX4w3LhY/O+2jt",
	"6aUwpLByay+dpD0FCUFJf43nN7sJzAT+eVRa8yr9tEJ4gX/OC/3dIvOfe+Y/bg4TcU366bn0A9HAcCEZ",
	"uJTtZekc9qbnfN4t2/vj7HO+7LapOXQwyR3OLe5Re7fNPONdc9fAxQ3TN5TiXc3Nzjm3+dY3N4z3KGef",
	"0a62lSc3wL+YpCuCUl823lC6hc3TN0mFdLw2qZMW5259ebntNGi75fi8fr9Wq5H9Su6s/17y4uKole8X",
	"rKzpZOb7mMWrrkyw6vA9uOJVV4ms4EKTa39zP/VHcIrH+up2abZ09HUCa1YcvsGarBJ28Mstk7/YmiwU",
	"l/yll8rdhk0Wy+Z6JXXMTIqz64UzYc1Ct6BSxrcoSIXbhHTaf7z/3wAAAP//wM8soAFNAAA=",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
